sudo: required
services:
  - docker

before_install:
  - docker build -t dimavedenyapin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dimavedenyapin/react-test npm test -- --coverage

after_success:
  - docker build -t dimavedenyapin/multi-client ./client
  - docker build -t dimavedenyapin/multi-nginx ./nginx
  - docker build -t dimavedenyapin/multi-server ./server
  - docker build -t dimavedenyapin/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take this images and push them to docker hub
  - docker push dimavedenyapin/multi-client
  - docker push dimavedenyapin/multi-nginx
  - docker push dimavedenyapin/multi-server
  - docker push dimavedenyapin/multi-worker
